name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Cache podman
        id: cache-podman
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/podman
          key: ${{ runner.os }}-podman

      - name: Cache zig binary
        id: cache-zig
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/zig
          key: ${{ runner.os }}-zig

      - name: Install podman
        if: steps.cache-podman.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/containers/podman/releases/download/v4.9.2/podman-remote-static-linux_amd64.tar.gz
          tar xf podman-remote-static-linux_amd64.tar.gz
          mv bin/podman-remote-static-linux_amd64 /usr/local/bin/podman

      - name: Setup connection to host podman socket
        run: |
          podman system connection add host unix:///var/run/docker.sock
          podman system connection list

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Container registry
        run: |
          podman version
          podman login git.cathal.xyz -u ${{ gitea.repository_owner }} -p ${{ secrets.GITEA_TOKEN }}

      - name: Install zig
        if: steps.cache-zig.outputs.cache-hit != 'true'
        run: |
          wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
          tar xf zig-linux-x86_64-0.11.0.tar.xz
          rm ./zig-linux-x86_64-0.11.0.tar.xz
          mv zig-linux-x86_64-0.11.0 /usr/local/bin
          ln -s /usr/local/bin/zig-linux-x86_64-0.11.0/zig /usr/local/bin/zig

      - name: Build zblog
        run: |
          find .
          zig build -Doptimize=ReleaseFast -Dtarget=x86_64-linux

      - name: Build and push the image
        run: |
          podman build . -t ${{ gitea.repository }}
          podman push git.cathal.xyz/${{ gitea.repository }}:${{ gitea.sha }}
          podman push git.cathal.xyz/${{ gitea.repository }}:latest
