name: Build And Test
run-name: ${{ gitea.actor }} is runs ci pipeline
on: [ push ]

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: gitea.ref == 'refs/head/main'
    steps:
      - uses: https://github.com/actions/checkout@v4
      - name: Setup Docker build
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry.gitea:3000]
            http = true
            insecure = true
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "gitea:3000/zblog:${{gitea.sha}},gitea:3000/zblog:latest"
